branches:
  only:
  - source

language: ruby
rvm: 2.0.0

sudo: false

before_install:
- git config --global user.name "tangleithu"
- git config --global user.email "travis@tanglei.name"
- gem list


install:
- gem install jekyll
- gem install i18n
- gem install jekyll-sitemap
- gem install jekyll-paginate
- gem install jekyll-coffeescript
- gem install jekyll-gist

script:
- git checkout source
- jekyll build

after_success:
- cd _site
- git init && git add -A . && git commit -m "commit from travis" 
- git push --force --quiet "https://tl3shi:$GITHUB_TOKEN@github.com/tl3shi/jekyll.tanglei.name.git" master:gh-pages
- git log | head -n 6
