branches:
  only:
  - source

language: ruby
rvm: 2.0.0

sudo: false

node_js:
    - 'stable'

before_install:
- git config --global user.name "tangleithu"
- git config --global user.email "travis@tanglei.name"

install:
- gem install jekyll

script:
- git checkout source
- jekyll build
- cd _site
- git init && git add -A . && git commit -m "commit from travis" 
- git push --force "https://tl3shi:$GITHUB_TOKEN@github.com/tl3shi/jekyll.tanglei.name.git" source:gh-pages 
