#---------------------------------------------------------------
# Theme version infromation
#---------------------------------------------------------------
version: 1.0

#---------------------------------------------------------------
# Build setting
#---------------------------------------------------------------
gems: 
    - jekyll-paginate
    - jekyll-sitemap
#    - jekyll-redirect-from

# Config sass build output by sass_dir
# Config sass output is compressed or not
#
sass:
    sass_dir: /assets/stylesheet
    style: :compressed


#---------------------------------------------------------------
# Site infromation setting
#---------------------------------------------------------------

# Site
## You can create a locale setting at _locales and name *.yml
title: tanglei's blog|唐磊的个人博客
subtitle: 记录我的学习、生活、工作。
description: 中南大学|清华大学软件学院唐磊的博客,主攻软件工程,数据挖掘,这里记录了我的学习,生活和工作
keywords: "唐磊, 中南大学, 清华大学, 软件工程师, 计算机, 全栈工程师"
locale: "zh_CN"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and baseurl as '/child/'
url: "http://www.tanglei.name"
baseurl: ""
#permalink: /:year/:month/:day/:title
permalink: /blog/:title.html


# Pagination
## Set per_page to 0 to disable pagination
paginate: 8
paginate_path: "/page/:num/"

# Writing
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
    extensions:
        - autolink
        - footnotes
        - smart

# RSS
rss:
  path: "/feed.xml"
  icon: "rss"

#---------------------------------------------------------------
# Authour infromation setting
#---------------------------------------------------------------

# Author
author:
  name: "tanglei"
  avatar: "/tx.jpg"
  motto: "码农 @ 宜信大数据创新中心, 毕业于CSU && THU,  曾工作于<a href='http://www.tencent.com/zh-cn/index.shtml' target='_blank'>腾讯</a> && <a href='http://www.umeng.com/' target='_blank'>友盟</a>.  &nbsp; <a href='/about/'> MORE </a>"

# Socials
## If you want the social show,place sure the social no comment
## The socials icon base font-awesome,you can learn more on http://fontawesome.io/icons/
socials:
    - name: "weibo"
      url: "http://www.weibo.com/tangleithu/"
      icon: "weibo"
    - name: "github"
      url: "https://github.com/tl3shi"
      icon: "github"
    - name: "facebook"
      url: "https://www.facebook.com/tanglei.name"
      icon: "facebook"




#---------------------------------------------------------------
# Site comment setting
#---------------------------------------------------------------

comment:
  enable: true

# duoshuo
duoshuo:
  enable: false
  short_name: "tangleithu"

# disqus
disqus:
  enable: true # network is not stable
  short_name: "hexo-tanglei"

#---------------------------------------------------------------
# Site share setting
#---------------------------------------------------------------
duoshuo_share:
    enable: false

#---------------------------------------------------------------
# Site analysis setting
#---------------------------------------------------------------
# Baidu analysis
baidu_analysis:
  enable: true
  token: "f0117177475f54027bfcaceb8d668cee"

# Google analysis
google_analysus:
  enable: false
  token: "your google analysis token"
