sed -i "" "/  - Halsteads/d" `ls *.md`
sed -i "" "/  - Programmers Health/d" `ls *.md`
sed -i "" "/  - .htaccess/d" `ls *.md`
sed -i "" "/  - 10010/d" `ls *.md`
sed -i "" "/  - 2010年/d" `ls *.md`
sed -i "" "/  - 2011腾讯hr面/d" `ls *.md`
sed -i "" "/  - 2011腾讯实习/d" `ls *.md`
sed -i "" "/  - 32位系统/d" `ls *.md`
sed -i "" "/  - 3次握手/d" `ls *.md`
sed -i "" "/  - 404 Not Found/d" `ls *.md`
sed -i "" "/  - 4Cs/d" `ls *.md`
sed -i "" "/  - 4G内存/d" `ls *.md`
sed -i "" "/  - 4Ps/d" `ls *.md`
sed -i "" "/  - 64位Win7/d" `ls *.md`
sed -i "" "/  - Android 4.2/d" `ls *.md`
sed -i "" "/  - Android手机信号/d" `ls *.md`
sed -i "" "/  - Android挑战赛/d" `ls *.md`
sed -i "" "/  - Android环境变量/d" `ls *.md`
sed -i "" "/  - AutoSwitcher/d" `ls *.md`
sed -i "" "/  - A记录/d" `ls *.md`
sed -i "" "/  - B\/S/d" `ls *.md`
sed -i "" "/  - Boehm/d" `ls *.md`
sed -i "" "/  - C\/S/d" `ls *.md`
sed -i "" "/  - CK/d" `ls *.md`
sed -i "" "/  - CMMI/d" `ls *.md`
sed -i "" "/  - CMM考试/d" `ls *.md`
sed -i "" "/  - CMM考点/d" `ls *.md`
sed -i "" "/  - COM接口/d" `ls *.md`
sed -i "" "/  - CoCoMo模型/d" `ls *.md`
sed -i "" "/  - DDL/d" `ls *.md`
sed -i "" "/  - DIP/d" `ls *.md`
sed -i "" "/  - DML/d" `ls *.md`
sed -i "" "/  - DN/d" `ls *.md`
sed -i "" "/  - Electronic Commerce/d" `ls *.md`
sed -i "" "/  - FP/d" `ls *.md`
sed -i "" "/  - FPU/d" `ls *.md`
sed -i "" "/  - Facade/d" `ls *.md`
sed -i "" "/  - Feature Point/d" `ls *.md`
sed -i "" "/  - Function Points/d" `ls *.md`
sed -i "" "/  - GFW/d" `ls *.md`
sed -i "" "/  - GPR/d" `ls *.md`
sed -i "" "/  - GPU/d" `ls *.md`
sed -i "" "/  - Game/d" `ls *.md`
sed -i "" "/  - GiftWrapping/d" `ls *.md`
sed -i "" "/  - Google API/d" `ls *.md`
sed -i "" "/  - Google Goggles/d" `ls *.md`
sed -i "" "/  - Google doodle/d" `ls *.md`
sed -i "" "/  - Google+1/d" `ls *.md`
sed -i "" "/  - Google优化SEO/d" `ls *.md`
sed -i "" "/  - Graham Scan/d" `ls *.md`
sed -i "" "/  - HR理论/d" `ls *.md`
sed -i "" "/  - HTTP状态码304原理/d" `ls *.md`
sed -i "" "/  - Hash Collision/d" `ls *.md`
sed -i "" "/  - Hash冲突/d" `ls *.md`
sed -i "" "/  - Henry and Kafura’s Metrics/d" `ls *.md`
sed -i "" "/  - ISO9126/d" `ls *.md`
sed -i "" "/  - ISP/d" `ls *.md`
sed -i "" "/  - IT项目管理模拟试题/d" `ls *.md`
sed -i "" "/  - If-Modified-Since/d" `ls *.md`
sed -i "" "/  - If-None-Match/d" `ls *.md`
sed -i "" "/  - JDBC/d" `ls *.md`
sed -i "" "/  - JDK/d" `ls *.md`
sed -i "" "/  - JS错误/d" `ls *.md`
sed -i "" "/  - Java教程/d" `ls *.md`
sed -i "" "/  - Java电子书/d" `ls *.md`
sed -i "" "/  - Java设计模式/d" `ls *.md`
sed -i "" "/  - LBS.位置服务/d" `ls *.md`
sed -i "" "/  - LK/d" `ls *.md`
sed -i "" "/  - LSP/d" `ls *.md`
sed -i "" "/  - Last-Modified/d" `ls *.md`
sed -i "" "/  - LoC/d" `ls *.md`
sed -i "" "/  - LoD/d" `ls *.md`
sed -i "" "/  - MB525/d" `ls *.md`
sed -i "" "/  - MUSiC/d" `ls *.md`
sed -i "" "/  - MX记录/d" `ls *.md`
sed -i "" "/  - McCabe/d" `ls *.md`
sed -i "" "/  - McCall/d" `ls *.md`
sed -i "" "/  - MicroSoft/d" `ls *.md`
sed -i "" "/  - MinGW/d" `ls *.md`
sed -i "" "/  - My Name Is E/d" `ls *.md`
sed -i "" "/  - Mysql/d" `ls *.md`
sed -i "" "/  - NF/d" `ls *.md`
sed -i "" "/  - Notification/d" `ls *.md`
sed -i "" "/  - OCP/d" `ls *.md`
sed -i "" "/  - OSI/d" `ls *.md`
sed -i "" "/  - Object Point/d" `ls *.md`
sed -i "" "/  - Openmesh/d" `ls *.md`
sed -i "" "/  - PHPECLILPSE/d" `ls *.md`
sed -i "" "/  - PR值更新/d" `ls *.md`
sed -i "" "/  - Page Rank/d" `ls *.md`
sed -i "" "/  - Proxy/d" `ls *.md`
sed -i "" "/  - QQ/d" `ls *.md`
sed -i "" "/  - QQ空间/d" `ls *.md`
sed -i "" "/  - QT/d" `ls *.md`
sed -i "" "/  - Qzhttp/d" `ls *.md`
sed -i "" "/  - RAMDISK/d" `ls *.md`
sed -i "" "/  - RDBM/d" `ls *.md`
sed -i "" "/  - RVO/d" `ls *.md`
sed -i "" "/  - RZ/d" `ls *.md`
sed -i "" "/  - SCM与CMM/d" `ls *.md`
sed -i "" "/  - SCM与CMMI/d" `ls *.md`
sed -i "" "/  - SCM功能/d" `ls *.md`
sed -i "" "/  - SCM基本活动/d" `ls *.md`
sed -i "" "/  - SCM工具对比/d" `ls *.md`
sed -i "" "/  - SCM工具比较/d" `ls *.md`
sed -i "" "/  - SCM概念/d" `ls *.md`
sed -i "" "/  - SCM目标/d" `ls *.md`
sed -i "" "/  - SCM职责/d" `ls *.md`
sed -i "" "/  - SCM阶段/d" `ls *.md`
sed -i "" "/  - SQL/d" `ls *.md`
sed -i "" "/  - SRP/d" `ls *.md`
sed -i "" "/  - SSD10/d" `ls *.md`
sed -i "" "/  - SZ/d" `ls *.md`
sed -i "" "/  - SecureCRT/d" `ls *.md`
sed -i "" "/  - Shepperd’s Metrics/d" `ls *.md`
sed -i "" "/  - SnapDat/d" `ls *.md`
sed -i "" "/  - Sosospider/d" `ls *.md`
sed -i "" "/  - TOMCAT配置CGI/d" `ls *.md`
sed -i "" "/  - TTC/d" `ls *.md`
sed -i "" "/  - UML/d" `ls *.md`
sed -i "" "/  - Ubuntu 4G/d" `ls *.md`
sed -i "" "/  - Ubuntu启动/d" `ls *.md`
sed -i "" "/  - Use-case Point/d" `ls *.md`
sed -i "" "/  - Vim快捷键/d" `ls *.md`
sed -i "" "/  - WIN7切换hosts工具/d" `ls *.md`
sed -i "" "/  - WRITE_SECURE_SETTING/d" `ls *.md`
sed -i "" "/  - Windows Linux命令/d" `ls *.md`
sed -i "" "/  - Windows MAC共享上网/d" `ls *.md`
sed -i "" "/  - XAMPP/d" `ls *.md`
sed -i "" "/  - Y430/d" `ls *.md`
sed -i "" "/  - __iadd__/d" `ls *.md`
sed -i "" "/  - __pycache__目录/d" `ls *.md`
sed -i "" "/  - adb/d" `ls *.md`
sed -i "" "/  - android保存短信/d" `ls *.md`
sed -i "" "/  - android启动另一个APK/d" `ls *.md`
sed -i "" "/  - android启动系统应用程序/d" `ls *.md`
sed -i "" "/  - android源码/d" `ls *.md`
sed -i "" "/  - android短信协议/d" `ls *.md`
sed -i "" "/  - android短信管理代码/d" `ls *.md`
sed -i "" "/  - android获取通讯录/d" `ls *.md`
sed -i "" "/  - android调试证书过期/d" `ls *.md`
sed -i "" "/  - apk/d" `ls *.md`
sed -i "" "/  - app2ext/d" `ls *.md`
sed -i "" "/  - app2sd/d" `ls *.md`
sed -i "" "/  - apriori/d" `ls *.md`
sed -i "" "/  - aprioriAll算法/d" `ls *.md`
sed -i "" "/  - array_merge/d" `ls *.md`
sed -i "" "/  - association rule/d" `ls *.md`
sed -i "" "/  - autocite的方式 /d" `ls *.md`
sed -i "" "/  - beamer /d" `ls *.md`
sed -i "" "/  - bezier/d" `ls *.md`
sed -i "" "/  - bezier曲线/d" `ls *.md`
sed -i "" "/  - bezier曲面/d" `ls *.md`
sed -i "" "/  - bib/d" `ls *.md`
sed -i "" "/  - bibtex/d" `ls *.md`
sed -i "" "/  - blog/d" `ls *.md`
sed -i "" "/  - blogilo/d" `ls *.md`
sed -i "" "/  - blog搬家/d" `ls *.md`
sed -i "" "/  - bluetooth/d" `ls *.md`
sed -i "" "/  - bowyer-watson/d" `ls *.md`
sed -i "" "/  - bulk collect/d" `ls *.md`
sed -i "" "/  - bump/d" `ls *.md`
sed -i "" "/  - cgi/d" `ls *.md`
sed -i "" "/  - class/d" `ls *.md`
sed -i "" "/  - codecolorer /d" `ls *.md`
sed -i "" "/  - config/d" `ls *.md`
sed -i "" "/  - cpp/d" `ls *.md`
sed -i "" "/  - datamining/d" `ls *.md`
sed -i "" "/  - de Casteljau算法/d" `ls *.md`
sed -i "" "/  - debug/d" `ls *.md`
sed -i "" "/  - delaunay/d" `ls *.md`
sed -i "" "/  - delete/d" `ls *.md`
sed -i "" "/  - design pattern/d" `ls *.md`
sed -i "" "/  - effective c++/d" `ls *.md`
sed -i "" "/  - emp/d" `ls *.md`
sed -i "" "/  - exam/d" `ls *.md`
sed -i "" "/  - ext/d" `ls *.md`
sed -i "" "/  - facebook/d" `ls *.md`
sed -i "" "/  - favicon.ico/d" `ls *.md`
sed -i "" "/  - fork/d" `ls *.md`
sed -i "" "/  - foxmail7导入邮箱/d" `ls *.md`
sed -i "" "/  - foxmail导入帐号/d" `ls *.md`
sed -i "" "/  - halfbriakin/d" `ls *.md`
sed -i "" "/  - hello world/d" `ls *.md`
sed -i "" "/  - highlight /d" `ls *.md`
sed -i "" "/  - init/d" `ls *.md`
sed -i "" "/  - ipv6/d" `ls *.md`
sed -i "" "/  - iteye/d" `ls *.md`
sed -i "" "/  - jar/d" `ls *.md`
sed -i "" "/  - javaeye/d" `ls *.md`
sed -i "" "/  - javascript/d" `ls *.md`
sed -i "" "/  - java支持CGI/d" `ls *.md`
sed -i "" "/  - jquery /d" `ls *.md`
sed -i "" "/  - latex /d" `ls *.md`
sed -i "" "/  - latex-suite/d" `ls *.md`
sed -i "" "/  - lawson/d" `ls *.md`
sed -i "" "/  - layout/d" `ls *.md`
sed -i "" "/  - leetcode/d" `ls *.md`
sed -i "" "/  - linux后台运行/d" `ls *.md`
sed -i "" "/  - linux命令/d" `ls *.md`
sed -i "" "/  - log/d" `ls *.md`
sed -i "" "/  - mac osx/d" `ls *.md`
sed -i "" "/  - matlab/d" `ls *.md`
sed -i "" "/  - mfc/d" `ls *.md`
sed -i "" "/  - milestone/d" `ls *.md`
sed -i "" "/  - mount/d" `ls *.md`
sed -i "" "/  - mysql_query/d" `ls *.md`
sed -i "" "/  - mysql漏洞/d" `ls *.md`
sed -i "" "/  - native/d" `ls *.md`
sed -i "" "/  - new/d" `ls *.md`
sed -i "" "/  - ntfs/d" `ls *.md`
sed -i "" "/  - octopress/d" `ls *.md`
sed -i "" "/  - php中文图片水印/d" `ls *.md`
sed -i "" "/  - php中文水印乱码/d" `ls *.md`
sed -i "" "/  - php文字水印/d" `ls *.md`
sed -i "" "/  - php文字水印乱码/d" `ls *.md`
sed -i "" "/  - piress帐户/d" `ls *.md`
sed -i "" "/  - ppt 模版/d" `ls *.md`
sed -i "" "/  - pyc文件/d" `ls *.md`
sed -i "" "/  - regular expression/d" `ls *.md`
sed -i "" "/  - requirements/d" `ls *.md`
sed -i "" "/  - robots.txt/d" `ls *.md`
sed -i "" "/  - scala /d" `ls *.md`
sed -i "" "/  - sequential pattern/d" `ls *.md`
sed -i "" "/  - software0804/d" `ls *.md`
sed -i "" "/  - strictfp/d" `ls *.md`
sed -i "" "/  - struct/d" `ls *.md`
sed -i "" "/  - subclipse/d" `ls *.md`
sed -i "" "/  - svn/d" `ls *.md`
sed -i "" "/  - tar/d" `ls *.md`
sed -i "" "/  - tcpdump/d" `ls *.md`
sed -i "" "/  - tell me why/d" `ls *.md`
sed -i "" "/  - thuflute/d" `ls *.md`
sed -i "" "/  - tlb文件/d" `ls *.md`
sed -i "" "/  - tomcat/d" `ls *.md`
sed -i "" "/  - transient/d" `ls *.md`
sed -i "" "/  - truncate/d" `ls *.md`
sed -i "" "/  - tsinghua /d" `ls *.md`
sed -i "" "/  - twitter/d" `ls *.md`
sed -i "" "/  - ubuntu桌面效果/d" `ls *.md`
sed -i "" "/  - volatile/d" `ls *.md`
sed -i "" "/  - web/d" `ls *.md`
sed -i "" "/  - whois/d" `ls *.md`
sed -i "" "/  - win7/d" `ls *.md`
sed -i "" "/  - windows7/d" `ls *.md`
sed -i "" "/  - windump/d" `ls *.md`
sed -i "" "/  - winrar破解/d" `ls *.md`
sed -i "" "/  - word/d" `ls *.md`
sed -i "" "/  - wordpress赚钱/d" `ls *.md`
sed -i "" "/  - worpress/d" `ls *.md`
sed -i "" "/  - wptouch /d" `ls *.md`
sed -i "" "/  - x64/d" `ls *.md`
sed -i "" "/  - x86/d" `ls *.md`
sed -i "" "/  - xcode/d" `ls *.md`
sed -i "" "/  - 万维网/d" `ls *.md`
sed -i "" "/  - 三库管理/d" `ls *.md`
sed -i "" "/  - 三系统/d" `ls *.md`
sed -i "" "/  - 三角剖分/d" `ls *.md`
sed -i "" "/  - 不关机后果/d" `ls *.md`
sed -i "" "/  - 专家推荐信/d" `ls *.md`
sed -i "" "/  - 个人经历/d" `ls *.md`
sed -i "" "/  - 个人陈述/d" `ls *.md`
sed -i "" "/  - 中南大学学工网/d" `ls *.md`
sed -i "" "/  - 中国联通/d" `ls *.md`
sed -i "" "/  - 中央处理器CPU/d" `ls *.md`
sed -i "" "/  - 中期检查/d" `ls *.md`
sed -i "" "/  - 主线/d" `ls *.md`
sed -i "" "/  - 书单/d" `ls *.md`
sed -i "" "/  - 书籍推荐/d" `ls *.md`
sed -i "" "/  - 亲情/d" `ls *.md`
sed -i "" "/  - 人人网/d" `ls *.md`
sed -i "" "/  - 代理/d" `ls *.md`
sed -i "" "/  - 代码走查/d" `ls *.md`
sed -i "" "/  - 代码高亮/d" `ls *.md`
sed -i "" "/  - 代码高亮 /d" `ls *.md`
sed -i "" "/  - 企业/d" `ls *.md`
sed -i "" "/  - 企业文化/d" `ls *.md`
sed -i "" "/  - 企业邮局/d" `ls *.md`
sed -i "" "/  - 企业邮箱/d" `ls *.md`
sed -i "" "/  - 优化/d" `ls *.md`
sed -i "" "/  - 优惠码/d" `ls *.md`
sed -i "" "/  - 传参/d" `ls *.md`
sed -i "" "/  - 作业管理/d" `ls *.md`
sed -i "" "/  - 作业调度/d" `ls *.md`
sed -i "" "/  - 作弊/d" `ls *.md`
sed -i "" "/  - 保研政策/d" `ls *.md`
sed -i "" "/  - 信号量/d" `ls *.md`
sed -i "" "/  - 信息流/d" `ls *.md`
sed -i "" "/  - 借书/d" `ls *.md`
sed -i "" "/  - 储存库/d" `ls *.md`
sed -i "" "/  - 免审稿费/d" `ls *.md`
sed -i "" "/  - 免试推荐/d" `ls *.md`
sed -i "" "/  - 免费获取百度文库内容/d" `ls *.md`
sed -i "" "/  - 入侵/d" `ls *.md`
sed -i "" "/  - 关系模型/d" `ls *.md`
sed -i "" "/  - 关系范式/d" `ls *.md`
sed -i "" "/  - 关系运算/d" `ls *.md`
sed -i "" "/  - 关联规则/d" `ls *.md`
sed -i "" "/  - 兼容性/d" `ls *.md`
sed -i "" "/  - 内存/d" `ls *.md`
sed -i "" "/  - 内聚/d" `ls *.md`
sed -i "" "/  - 冒烟测试/d" `ls *.md`
sed -i "" "/  - 凤凰旅游/d" `ls *.md`
sed -i "" "/  - 凸包/d" `ls *.md`
sed -i "" "/  - 出错解释/d" `ls *.md`
sed -i "" "/  - 函数依赖/d" `ls *.md`
sed -i "" "/  - 分布式数据库/d" `ls *.md`
sed -i "" "/  - 分类/d" `ls *.md`
sed -i "" "/  - 创新论坛/d" `ls *.md`
sed -i "" "/  - 前十名/d" `ls *.md`
sed -i "" "/  - 前端 /d" `ls *.md`
sed -i "" "/  - 功能性/d" `ls *.md`
sed -i "" "/  - 加密技术/d" `ls *.md`
sed -i "" "/  - 北戴河/d" `ls *.md`
sed -i "" "/  - 博客赚钱/d" `ls *.md`
sed -i "" "/  - 反射/d" `ls *.md`
sed -i "" "/  - 反战/d" `ls *.md`
sed -i "" "/  - 反编译/d" `ls *.md`
sed -i "" "/  - 发布sdk/d" `ls *.md`
sed -i "" "/  - 发言/d" `ls *.md`
sed -i "" "/  - 发送短信/d" `ls *.md`
sed -i "" "/  - 变更管理/d" `ls *.md`
sed -i "" "/  - 另类设计模式/d" `ls *.md`
sed -i "" "/  - 可靠性评价/d" `ls *.md`
sed -i "" "/  - 右键菜单/d" `ls *.md`
sed -i "" "/  - 名片/d" `ls *.md`
sed -i "" "/  - 启动另外APK/d" `ls *.md`
sed -i "" "/  - 周例会/d" `ls *.md`
sed -i "" "/  - 周末加班/d" `ls *.md`
sed -i "" "/  - 唐磊/d" `ls *.md`
sed -i "" "/  - 团队合作/d" `ls *.md`
sed -i "" "/  - 固定链接失效/d" `ls *.md`
sed -i "" "/  - 图形和图像/d" `ls *.md`
sed -i "" "/  - 图形学/d" `ls *.md`
sed -i "" "/  - 图片拼接/d" `ls *.md`
sed -i "" "/  - 圆通/d" `ls *.md`
sed -i "" "/  - 垃圾信息/d" `ls *.md`
sed -i "" "/  - 域名/d" `ls *.md`
sed -i "" "/  - 域名续费/d" `ls *.md`
sed -i "" "/  - 域名邮箱/d" `ls *.md`
sed -i "" "/  - 基带信号/d" `ls *.md`
sed -i "" "/  - 基础/d" `ls *.md`
sed -i "" "/  - 基线管理/d" `ls *.md`
sed -i "" "/  - 外观模式/d" `ls *.md`
sed -i "" "/  - 外部属性度量/d" `ls *.md`
sed -i "" "/  - 多媒体/d" `ls *.md`
sed -i "" "/  - 大三上教学安排/d" `ls *.md`
sed -i "" "/  - 大学生创新性实验计划项目/d" `ls *.md`
sed -i "" "/  - 大学考试/d" `ls *.md`
sed -i "" "/  - 大小写区分/d" `ls *.md`
sed -i "" "/  - 大街营销方式/d" `ls *.md`
sed -i "" "/  - 天龙峡/d" `ls *.md`
sed -i "" "/  - 好玩的验证码/d" `ls *.md`
sed -i "" "/  - 子网掩码/d" `ls *.md`
sed -i "" "/  - 存储器系统/d" `ls *.md`
sed -i "" "/  - 存储管理/d" `ls *.md`
sed -i "" "/  - 学习/d" `ls *.md`
sed -i "" "/  - 学位授予/d" `ls *.md`
sed -i "" "/  - 学位论文答辩 /d" `ls *.md`
sed -i "" "/  - 学术/d" `ls *.md`
sed -i "" "/  - 学硕/d" `ls *.md`
sed -i "" "/  - 安全/d" `ls *.md`
sed -i "" "/  - 实习待遇/d" `ls *.md`
sed -i "" "/  - 实习报告/d" `ls *.md`
sed -i "" "/  - 实习行程/d" `ls *.md`
sed -i "" "/  - 对象点/d" `ls *.md`
sed -i "" "/  - 导师/d" `ls *.md`
sed -i "" "/  - 封锁协议/d" `ls *.md`
sed -i "" "/  - 就业/d" `ls *.md`
sed -i "" "/  - 局域网/d" `ls *.md`
sed -i "" "/  - 工学硕士/d" `ls *.md`
sed -i "" "/  - 广域网/d" `ls *.md`
sed -i "" "/  - 序列模式/d" `ls *.md`
sed -i "" "/  - 影响力/d" `ls *.md`
sed -i "" "/  - 微博秀/d" `ls *.md`
sed -i "" "/  - 微电影/d" `ls *.md`
sed -i "" "/  - 微软秋令营/d" `ls *.md`
sed -i "" "/  - 快递/d" `ls *.md`
sed -i "" "/  - 快速切换hosts脚本/d" `ls *.md`
sed -i "" "/  - 快速发布博客/d" `ls *.md`
sed -i "" "/  - 怀柔/d" `ls *.md`
sed -i "" "/  - 感人/d" `ls *.md`
sed -i "" "/  - 成都国际软件设计与应用大赛/d" `ls *.md`
sed -i "" "/  - 手机基带/d" `ls *.md`
sed -i "" "/  - 手机广告/d" `ls *.md`
sed -i "" "/  - 手语/d" `ls *.md`
sed -i "" "/  - 打包/d" `ls *.md`
sed -i "" "/  - 扫描仪/d" `ls *.md`
sed -i "" "/  - 批量导出/d" `ls *.md`
sed -i "" "/  - 技术/d" `ls *.md`
sed -i "" "/  - 投诉/d" `ls *.md`
sed -i "" "/  - 护照/d" `ls *.md`
sed -i "" "/  - 拒绝服务/d" `ls *.md`
sed -i "" "/  - 拷贝构造函数/d" `ls *.md`
sed -i "" "/  - 换专业/d" `ls *.md`
sed -i "" "/  - 换域名/d" `ls *.md`
sed -i "" "/  - 换空间/d" `ls *.md`
sed -i "" "/  - 换行符/d" `ls *.md`
sed -i "" "/  - 控制流/d" `ls *.md`
sed -i "" "/  - 控制流结构/d" `ls *.md`
sed -i "" "/  - 插件/d" `ls *.md`
sed -i "" "/  - 搜索引擎/d" `ls *.md`
sed -i "" "/  - 搭建博客/d" `ls *.md`
sed -i "" "/  - 操作系统类型/d" `ls *.md`
sed -i "" "/  - 支持向量机/d" `ls *.md`
sed -i "" "/  - 支教/d" `ls *.md`
sed -i "" "/  - 改域名/d" `ls *.md`
sed -i "" "/  - 放假/d" `ls *.md`
sed -i "" "/  - 教程/d" `ls *.md`
sed -i "" "/  - 数字水印/d" `ls *.md`
sed -i "" "/  - 数字签名/d" `ls *.md`
sed -i "" "/  - 数学基础知识/d" `ls *.md`
sed -i "" "/  - 数据仓库/d" `ls *.md`
sed -i "" "/  - 数据压缩/d" `ls *.md`
sed -i "" "/  - 数据库保护/d" `ls *.md`
sed -i "" "/  - 数据库故障/d" `ls *.md`
sed -i "" "/  - 数据库系统结构/d" `ls *.md`
sed -i "" "/  - 数据模型/d" `ls *.md`
sed -i "" "/  - 数据类型/d" `ls *.md`
sed -i "" "/  - 数组/d" `ls *.md`
sed -i "" "/  - 文件/d" `ls *.md`
sed -i "" "/  - 文件和文件系统/d" `ls *.md`
sed -i "" "/  - 旁注/d" `ls *.md`
sed -i "" "/  - 旅游跟团/d" `ls *.md`
sed -i "" "/  - 日期函数/d" `ls *.md`
sed -i "" "/  - 日本交流/d" `ls *.md`
sed -i "" "/  - 明文传输/d" `ls *.md`
sed -i "" "/  - 暧昧/d" `ls *.md`
sed -i "" "/  - 最年轻教授/d" `ls *.md`
sed -i "" "/  - 最简单发布博客方法/d" `ls *.md`
sed -i "" "/  - 服务器/d" `ls *.md`
sed -i "" "/  - 服务质量/d" `ls *.md`
sed -i "" "/  - 本科生发表论文/d" `ls *.md`
sed -i "" "/  - 标兵/d" `ls *.md`
sed -i "" "/  - 校园网/d" `ls *.md`
sed -i "" "/  - 模拟试卷/d" `ls *.md`
sed -i "" "/  - 模拟试题/d" `ls *.md`
sed -i "" "/  - 正则表达式修饰符/d" `ls *.md`
sed -i "" "/  - 每日构建/d" `ls *.md`
sed -i "" "/  - 毕业/d" `ls *.md`
sed -i "" "/  - 毕业生代表/d" `ls *.md`
sed -i "" "/  - 水果忍者/d" `ls *.md`
sed -i "" "/  - 水长城/d" `ls *.md`
sed -i "" "/  - 汇编/d" `ls *.md`
sed -i "" "/  - 汉得实习生/d" `ls *.md`
sed -i "" "/  - 汉得面试/d" `ls *.md`
sed -i "" "/  - 沱江/d" `ls *.md`
sed -i "" "/  - 泛型/d" `ls *.md`
sed -i "" "/  - 泛型优缺点/d" `ls *.md`
sed -i "" "/  - 注销大街帐号/d" `ls *.md`
sed -i "" "/  - 流量包/d" `ls *.md`
sed -i "" "/  - 测量尺度类型/d" `ls *.md`
sed -i "" "/  - 浙大研究生面试/d" `ls *.md`
sed -i "" "/  - 浮点乘法/d" `ls *.md`
sed -i "" "/  - 浮点数/d" `ls *.md`
sed -i "" "/  - 消息摘要/d" `ls *.md`
sed -i "" "/  - 深圳欢乐谷/d" `ls *.md`
sed -i "" "/  - 深圳腾讯实习/d" `ls *.md`
sed -i "" "/  - 深圳腾讯实习报道/d" `ls *.md`
sed -i "" "/  - 清华大学保研复试/d" `ls *.md`
sed -i "" "/  - 游记/d" `ls *.md`
sed -i "" "/  - 湖南大学生/d" `ls *.md`
sed -i "" "/  - 湖南省/d" `ls *.md`
sed -i "" "/  - 澳门旅游/d" `ls *.md`
sed -i "" "/  - 牛人/d" `ls *.md`
sed -i "" "/  - 物流/d" `ls *.md`
sed -i "" "/  - 特征点/d" `ls *.md`
sed -i "" "/  - 特效/d" `ls *.md`
sed -i "" "/  - 王婆婆/d" `ls *.md`
sed -i "" "/  - 班长/d" `ls *.md`
sed -i "" "/  - 用例点/d" `ls *.md`
sed -i "" "/  - 用户体验/d" `ls *.md`
sed -i "" "/  - 用户界面/d" `ls *.md`
sed -i "" "/  - 电子商务概述/d" `ls *.md`
sed -i "" "/  - 电子商务类型/d" `ls *.md`
sed -i "" "/  - 电子安全体系/d" `ls *.md`
sed -i "" "/  - 电子支付/d" `ls *.md`
sed -i "" "/  - 电子认证/d" `ls *.md`
sed -i "" "/  - 电子货币/d" `ls *.md`
sed -i "" "/  - 相关文章/d" `ls *.md`
sed -i "" "/  - 相册/d" `ls *.md`
sed -i "" "/  - 短信发送/d" `ls *.md`
sed -i "" "/  - 研究生/d" `ls *.md`
sed -i "" "/  - 研究生面试/d" `ls *.md`
sed -i "" "/  - 破解百度文库/d" `ls *.md`
sed -i "" "/  - 社会工作/d" `ls *.md`
sed -i "" "/  - 神经猫/d" `ls *.md`
sed -i "" "/  - 离别/d" `ls *.md`
sed -i "" "/  - 离散数学/d" `ls *.md`
sed -i "" "/  - 私有工作区/d" `ls *.md`
sed -i "" "/  - 科协/d" `ls *.md`
sed -i "" "/  - 科学技术协会/d" `ls *.md`
sed -i "" "/  - 科研/d" `ls *.md`
sed -i "" "/  - 移动/d" `ls *.md`
sed -i "" "/  - 程序员/d" `ls *.md`
sed -i "" "/  - 程序员健康/d" `ls *.md`
sed -i "" "/  - 程序语言/d" `ls *.md`
sed -i "" "/  - 空指针异常/d" `ls *.md`
sed -i "" "/  - 笛协/d" `ls *.md`
sed -i "" "/  - 简单工厂/d" `ls *.md`
sed -i "" "/  - 简历/d" `ls *.md`
sed -i "" "/  - 系统短信/d" `ls *.md`
sed -i "" "/  - 系统程序/d" `ls *.md`
sed -i "" "/  - 纯代码实现/d" `ls *.md`
sed -i "" "/  - 纳网/d" `ls *.md`
sed -i "" "/  - 继承/d" `ls *.md`
sed -i "" "/  - 缓冲区/d" `ls *.md`
sed -i "" "/  - 编码技术标准/d" `ls *.md`
sed -i "" "/  - 编程大赛/d" `ls *.md`
sed -i "" "/  - 编程语言/d" `ls *.md`
sed -i "" "/  - 网站空间/d" `ls *.md`
sed -i "" "/  - 网络协议/d" `ls *.md`
sed -i "" "/  - 网络管理/d" `ls *.md`
sed -i "" "/  - 网络营销/d" `ls *.md`
sed -i "" "/  - 网络营销方式/d" `ls *.md`
sed -i "" "/  - 网络蜘蛛/d" `ls *.md`
sed -i "" "/  - 群硕实习生/d" `ls *.md`
sed -i "" "/  - 群硕面试/d" `ls *.md`
sed -i "" "/  - 翻墙/d" `ls *.md`
sed -i "" "/  - 考点总结/d" `ls *.md`
sed -i "" "/  - 考点答案/d" `ls *.md`
sed -i "" "/  - 考试复习资料/d" `ls *.md`
sed -i "" "/  - 耦合/d" `ls *.md`
sed -i "" "/  - 能力成熟度模型/d" `ls *.md`
sed -i "" "/  - 腾讯一面/d" `ls *.md`
sed -i "" "/  - 腾讯三面/d" `ls *.md`
sed -i "" "/  - 腾讯二面/d" `ls *.md`
sed -i "" "/  - 腾讯二面结果/d" `ls *.md`
sed -i "" "/  - 腾讯实习日子/d" `ls *.md`
sed -i "" "/  - 腾讯实习生offer/d" `ls *.md`
sed -i "" "/  - 腾讯实习生培训/d" `ls *.md`
sed -i "" "/  - 腾讯实习生待遇/d" `ls *.md`
sed -i "" "/  - 腾讯实习生报道/d" `ls *.md`
sed -i "" "/  - 腾讯实习生活/d" `ls *.md`
sed -i "" "/  - 腾讯实习生生活/d" `ls *.md`
sed -i "" "/  - 腾讯实习生留用考核/d" `ls *.md`
sed -i "" "/  - 腾讯技术一面/d" `ls *.md`
sed -i "" "/  - 腾讯技术二面/d" `ls *.md`
sed -i "" "/  - 腾讯笔试/d" `ls *.md`
sed -i "" "/  - 腾讯部门旅游/d" `ls *.md`
sed -i "" "/  - 自动/d" `ls *.md`
sed -i "" "/  - 自我调节/d" `ls *.md`
sed -i "" "/  - 节假日/d" `ls *.md`
sed -i "" "/  - 苦逼的程序员/d" `ls *.md`
sed -i "" "/  - 苦逼程序员/d" `ls *.md`
sed -i "" "/  - 范式/d" `ls *.md`
sed -i "" "/  - 获取联系人信息/d" `ls *.md`
sed -i "" "/  - 营销理论/d" `ls *.md`
sed -i "" "/  - 蓝牙/d" `ls *.md`
sed -i "" "/  - 虚拟硬盘/d" `ls *.md`
sed -i "" "/  - 表彰/d" `ls *.md`
sed -i "" "/  - 装B/d" `ls *.md`
sed -i "" "/  - 装饰器/d" `ls *.md`
sed -i "" "/  - 西北旅游/d" `ls *.md`
sed -i "" "/  - 规范化理论/d" `ls *.md`
sed -i "" "/  - 视频/d" `ls *.md`
sed -i "" "/  - 触发器/d" `ls *.md`
sed -i "" "/  - 计算机体系结构/d" `ls *.md`
sed -i "" "/  - 计算机保研复试/d" `ls *.md`
sed -i "" "/  - 计算机推免生面试/d" `ls *.md`
sed -i "" "/  - 计算机的安全/d" `ls *.md`
sed -i "" "/  - 计算机系统/d" `ls *.md`
sed -i "" "/  - 设备管理/d" `ls *.md`
sed -i "" "/  - 证书登记/d" `ls *.md`
sed -i "" "/  - 评优/d" `ls *.md`
sed -i "" "/  - 误删/d" `ls *.md`
sed -i "" "/  - 误差/d" `ls *.md`
sed -i "" "/  - 读书笔记/d" `ls *.md`
sed -i "" "/  - 调度算法/d" `ls *.md`
sed -i "" "/  - 谷歌logo/d" `ls *.md`
sed -i "" "/  - 质量模型/d" `ls *.md`
sed -i "" "/  - 贪婪匹配/d" `ls *.md`
sed -i "" "/  - 贪婪模式/d" `ls *.md`
sed -i "" "/  - 资源文件/d" `ls *.md`
sed -i "" "/  - 超流量/d" `ls *.md`
sed -i "" "/  - 越南旅游/d" `ls *.md`
sed -i "" "/  - 跨域访问/d" `ls *.md`
sed -i "" "/  - 跨平台/d" `ls *.md`
sed -i "" "/  - 转租/d" `ls *.md`
sed -i "" "/  - 软件工程保研/d" `ls *.md`
sed -i "" "/  - 软件配置管理文档/d" `ls *.md`
sed -i "" "/  - 软件配置管理流程/d" `ls *.md`
sed -i "" "/  - 返回值优化/d" `ls *.md`
sed -i "" "/  - 进程/d" `ls *.md`
sed -i "" "/  - 进程后台执行/d" `ls *.md`
sed -i "" "/  - 进程管理/d" `ls *.md`
sed -i "" "/  - 远程控制/d" `ls *.md`
sed -i "" "/  - 远程桌面/d" `ls *.md`
sed -i "" "/  - 透明水印/d" `ls *.md`
sed -i "" "/  - 通知栏/d" `ls *.md`
sed -i "" "/  - 邮政局/d" `ls *.md`
sed -i "" "/  - 配置管理角色/d" `ls *.md`
sed -i "" "/  - 配送/d" `ls *.md`
sed -i "" "/  - 采访/d" `ls *.md`
sed -i "" "/  - 里程碑/d" `ls *.md`
sed -i "" "/  - 重庆29中/d" `ls *.md`
sed -i "" "/  - 重庆到深圳/d" `ls *.md`
sed -i "" "/  - 门面模式/d" `ls *.md`
sed -i "" "/  - 防水/d" `ls *.md`
sed -i "" "/  - 防盗链/d" `ls *.md`
sed -i "" "/  - 隐私/d" `ls *.md`
sed -i "" "/  - 需求变更/d" `ls *.md`
sed -i "" "/  - 需求工程/d" `ls *.md`
sed -i "" "/  - 青春岁月/d" `ls *.md`
sed -i "" "/  - 面向对象设计原则/d" `ls *.md`
sed -i "" "/  - 面向对象软件度量/d" `ls *.md`
sed -i "" "/  - 面试题/d" `ls *.md`
sed -i "" "/  - 音频/d" `ls *.md`
sed -i "" "/  - 音频设备/d" `ls *.md`
sed -i "" "/  - 项目/d" `ls *.md`
sed -i "" "/  - 项目经验/d" `ls *.md`
sed -i "" "/  - 饭卡/d" `ls *.md`
sed -i "" "/  - 香港旅游/d" `ls *.md`
sed -i "" "/  - 骗子/d" `ls *.md`
sed -i "" "/  - 高08级14班/d" `ls *.md`
sed -i "" "/  - 魔力日志/d" `ls *.md`
sed -i "" "/  - 黑客/d" `ls *.md`
sed -i "" "/  - 龙场镇小学/d" `ls *.md`
